// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7aeS9-OTjosn6o6AvX5X4VPZRq8m0XcY',
    appId: '1:58453714103:web:22f9b1760a78f40aa6d932',
    messagingSenderId: '58453714103',
    projectId: 'kyle4-fb461',
    authDomain: 'kyle4-fb461.firebaseapp.com',
    storageBucket: 'kyle4-fb461.appspot.com',
    measurementId: 'G-CPMK256MTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS_X_asUqGywIsHmET_6fsQc2_Bn0dZx8',
    appId: '1:58453714103:android:00fbc7e25df8b894a6d932',
    messagingSenderId: '58453714103',
    projectId: 'kyle4-fb461',
    storageBucket: 'kyle4-fb461.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGLNMhCGYxCdayHsnGnONJcXasrJctKf0',
    appId: '1:58453714103:ios:4e2cf7f2b07200b5a6d932',
    messagingSenderId: '58453714103',
    projectId: 'kyle4-fb461',
    storageBucket: 'kyle4-fb461.appspot.com',
    iosClientId: '58453714103-tr0oub7eahku79s29vo3hpf33hk352ro.apps.googleusercontent.com',
    iosBundleId: 'com.example.kyle4app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGLNMhCGYxCdayHsnGnONJcXasrJctKf0',
    appId: '1:58453714103:ios:4e2cf7f2b07200b5a6d932',
    messagingSenderId: '58453714103',
    projectId: 'kyle4-fb461',
    storageBucket: 'kyle4-fb461.appspot.com',
    iosClientId: '58453714103-tr0oub7eahku79s29vo3hpf33hk352ro.apps.googleusercontent.com',
    iosBundleId: 'com.example.kyle4app',
  );
}
